# General parameters
system:
    name: Ca2+
    isotope: 
    include_breit: True

# Parameters used by basis programs
basis:
    cavity_radius: 55
    orbitals:
        core: 1s 2s 2p 3s 3p
        valence: 4s 4p 3d 5s 5p 4d 6s 6p 5d 4f
    b_splines:
        nmax: 40
        lmax: 6
        k: 7
    val_aov:
        s: 6
        p: 6
        d: 6
        f: 4
        g: 2
    val_energies:
        kval: 1
        energies: 
            s: -0.28000
            p: [-0.22000, -0.22000]
            d: [-0.31000, -0.31000]
            f: [-0.13000, -0.13000]

# Parameters used by add program
add:
    # Set of even and odd parity reference configurations
    ref_configs:
        odd: 
        even: [
            
        ]
    basis_set: 17spdfg
    orbitals:
        core:
        active: [
            1-2s: 2  2,
            2p: 6  6,
            3-7p:  0  6,
            3-7d:  0  6,
            4-5f:  0  6,
            ]    
    excitations:
        single: True
        double: True
        triple: False
    generate_directories: False

# Parameters used by conf program
conf:
    J: 0.0
    JM: 0.0
    num_energy_levels: 5
    num_dvdsn_iterations: 50
    
# Optional parameters
optional:
    qed:
        include: False
        rotate_basis: False

    isotope_shifts: 
        include: False
        K_is: 1
        C_is: 0.01

    code_exec: ci+all-order
    run_ao_codes: True