# System parameters
system:
    bin_directory: ""
    generate_directories: False
    run_codes: True
    on_hpc: True
    pci_version: default

# HPC parameters
hpc:
    partition: large-mem
    nodes: 1
    tasks_per_node: 64
    submit_job = False

# Atomic information
atom:
    name: Sr
    isotope: 
    include_breit: True
    code_method: [ci+all-order, ci+second-order]

# Parameters used by basis programs
basis:
    cavity_radius: 70
    diagonalized: True
    orbitals:
        core: 1s 2s 2p 3s 3p 3d 4s 4p 
        valence: 5s 5p 4d 6s 6p 5d 7s 7p 6d
        nmax: 35
        lmax: 5
    b_splines:
        nmax: 40
        lmax: 6
        k: 7
    val_aov:
        s: 5
        p: 5
        d: 5
        f: 3
    val_energies:
        kval: 1
        energies: 
            s: -0.28000
            p: [-0.22000, -0.22000]
            d: [-0.31000, -0.31000]
            f: [-0.13000, -0.13000]

# Parameters used by add program
add:
    # Lists of even and odd parity reference configurations
    ref_configs:
        odd: [5s1   5p1]
        even: [5s2]
    basis_set: 17spdfg
    orbitals:
        core: 1s 2s 2p 3s 3p 3d 4s 4p 
        active: [
            4-7p:  0  4,
            4-7d:  0  4,
            4-7f:  0  4,
            5-7g:  0  4,
            ]    
    excitations:
        single: True
        double: True
        triple: False

# Parameters used by conf program
conf:
    odd:
        J: 1.0
        JM: 1.0
        J_selection: False
        num_energy_levels: 12
        num_dvdsn_iterations: 50
    even:
        J: 0.0
        JM: 0.0
        J_selection: False
        num_energy_levels: 24
        num_dvdsn_iterations: 50
    include_lsj: True
    write_hij: True

# Parameters used by dtm program
dtm:
    include_rpa: True
    DM: 
        matrix_elements: 
        level_range: 
            odd: 
            even: 
    TM:
        matrix_elements: E1
        from:
            parity: odd
            level_range: 1 3
        to:
            parity: even 
            level_range: 1 1

# Parameters used by pol program
pol:
    parity: even
    level: 1
    method: 1
    field_type: static, dynamic
    wavelength_range: 1000 1000
    step_size: 0
    
# Optional parameters
optional:
    qed:
        include: False

    isotope_shifts: 
        include: False
        K_is: 0
        C_is: 0
