name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Install Fortran compiler
      - name: Setup Fortran
        uses: fortran-lang/setup-fortran@v1.6.1
        with:
          compiler: intel
          version: 2024.1

      # Install Intel MKL library
      - name: Setup MKL
        run: |
          sudo apt install intel-oneapi-mkl

      # Install OpenMPI
      - name: Install OpenMPI
        run: |
          wget https://download.open-mpi.org/release/open-mpi/v5.0/openmpi-5.0.3.tar.gz
          tar -xzf openmpi-5.0.3.tar.gz
          ./openmpi-5.0.3/configure --prefix=/home/${USER}/openmpi CC=icx CXX=icpx FC=ifx
          make -j$(nproc)
          make install

      # Install CMake
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2.0.2
        with:
          cmake-version: '3.13'

      # Build the project with CMake
      - name: Build
        run: |
          export MKLROOT=/opt/intel/oneapi/mkl/latest
          export LD_LIBRARY_PATH=$MKLROOT/lib/intel64:$LD_LIBRARY_PATH
          export LIBRARY_PATH=$MKLROOT/lib/intel64:$LIBRARY_PATH
          export CPATH=$MKLROOT/include:$CPATH
          mkdir -p build
          cd build
          FC=ifx cmake -DMPI_Fortran_COMPILER=mpifort -DMPI_HOME=/home/${USER}/openmpi -DCMAKE_INSTALL_PREFIX=$(pwd)/../ ..
          make
          make install
